### ISSUE TITLE
Unable to back up app data

### ISSUE THREAD

**Issue by starlordabell1835** [Pool-Of-Tears/GreenStash#54]
Getting this error message when I click Backup App Data:
https://snipboard.io/Tj710L.jpg

Following are the error details I've copied:
```
Build version: 2.7.0 
Current date: 2023-08-25 19:15:05 
Device: LGE A001LG 
OS version: Android 11 (SDK 30) 
 
Stack trace:  
com.google.crypto.tink.shaded.protobuf.z: Protocol message contained an invalid tag (zero).
	at com.google.crypto.tink.shaded.protobuf.e.F(SourceFile:157)
	at com.google.crypto.tink.shaded.protobuf.s0.C(SourceFile:756)
	at com.google.crypto.tink.shaded.protobuf.s0.h(Unknown Source:4)
	at com.google.crypto.tink.shaded.protobuf.e.o(Unknown Source:28)
	at com.google.crypto.tink.shaded.protobuf.e.p(Unknown Source:0)
	at com.google.crypto.tink.shaded.protobuf.s0.C(SourceFile:554)
	at com.google.crypto.tink.shaded.protobuf.s0.h(Unknown Source:4)
	at com.google.crypto.tink.shaded.protobuf.w.r(SourceFile:34)
	at z7.c0.C(Unknown Source:2)
	at u7.a$a.a(SourceFile:56)
	at y9.h.E(SourceFile:376)
	at y9.h.C(SourceFile:12)
	at b9.d.F(SourceFile:10)
	at s.w$b.g0(SourceFile:17)
	at t.e1$a.l(SourceFile:134)
	at ha.a.q(Unknown Source:8)
	at h1.c.D0(Unknown Source:77)
	at wa.j.r(SourceFile:129)
	at wa.j.E(SourceFile:44)
	at wa.j.q(SourceFile:17)
	at j1.e0.O(SourceFile:51)
	at j1.e0.G(Unknown Source:8)
	at o1.c.p(Unknown Source:13)
	at j1.j.e(SourceFile:85)
	at j1.j.e(SourceFile:71)
	at j1.j.e(SourceFile:71)
	at j1.j.e(SourceFile:71)
	at j1.j.e(SourceFile:71)
	at j1.j.e(SourceFile:71)
	at j1.j.e(SourceFile:71)
	at j1.k.e(SourceFile:26)
	at j1.v.a(SourceFile:183)
	at androidx.compose.ui.platform.AndroidComposeView.L(SourceFile:78)
	at androidx.compose.ui.platform.AndroidComposeView.B(SourceFile:249)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(SourceFile:88)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3203)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2875)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3203)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2875)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3203)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2875)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3203)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2875)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3203)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2875)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3203)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2875)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:529)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1880)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4144)
	at h.h.dispatchTouchEvent(Unknown Source:2)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:487)
	at android.view.View.dispatchPointerEvent(View.java:14582)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6277)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6080)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5514)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5571)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5537)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5545)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5518)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5571)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5537)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5706)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5545)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5763)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5518)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5571)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5537)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5545)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5518)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8426)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8375)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8335)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8577)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:221)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:183)
	at android.app.ActivityThread.main(ActivityThread.java:7887)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
	Suppressed: wa.k0: [androidx.compose.ui.platform.e2@b7d0a7e, i0.e@8e40bdf, x1{Cancelling}@231302c, x0@9a71af5]

```
What do you think is the issue? Need to back up data ASAP.

**Comment by starry-shivam** [comment]
Looks like some encryption related issue, have you tried clearing the app cache?
Current backup functionality is kind of messy as it dumps whole database as a backup file which is error prone, I've plans to rewrite backup & restore it once i get time (hopefully soon)

**Comment by starlordabell1835** [comment]
The first thing I did was to clear the cache but that didn't work.

I want to clear data and reinstall, but I'm afraid I'll lose whatever changes I've made in the app without first backing up.

**Comment by starry-shivam** [comment]
Sorry, but i can't figure out what exactly is causing this issue, my guess is, there's some data which can't be serialised or there is some encryption related issue with room database, anyhow i don't know how to make it work for you right now. I will try to investigate and fix this problem in future releases.
